% Filter design for parallel-gs NTSC/PAL filtering.
pkg load signal;

% As defined by BT.601.
bt601_rate = 13.5e6;

% The subclock of PS2 seems to be 4x BT.601 rate.
subpixel_rate = 4 * bt601_rate;
subpixel_nyquist = subpixel_rate / 2;

ntsc_subcarrier = 315e6 / 88;
pal_subcarrier = 4.43361875e6;

% Grabbed some sensible values from a paper that discusses a physical NTSC/PAL impl in 1997,
% so it looks plausible that PS2 would ship something similar.
luma_bw = 4.2e6;
luma_stop = 6.75e6;
chroma_bw = 1.0e6;
chroma_stop = 2.0e6;

% First stage of downsampling from 54 MHz to 27 MHz.
% Assume some zero-order hold behavior coming out of the CRTC due to its subclock behavior.
% Most likely it's just holding pixels until the horizontal divider clocks enough times.
% 640 * 4 = 2560
% 512 * 5 = 2560
% 256 * 10 = 2560
% etc ...
% Allow some aliasing to go through to keep filter length reasonable.
% We'll filter that away in the next pass.
downsampling_filter = firls(14, [0, luma_bw * 1.2, subpixel_nyquist * 0.7, subpixel_nyquist] / subpixel_nyquist, [1 1 0 0]);

% Encode filters at 27 MHz. Pure low-pass.
%luma_lp_encode = fir1(30, 0.3689, 'low', kaiser(31, 8.0))'
luma_lp_encode = firls(30, [0, luma_bw, luma_stop, bt601_rate] / bt601_rate, [1 1 0 0]);
chroma_lp_encode = firls(30, [0, chroma_bw, chroma_stop, bt601_rate] / bt601_rate, [1 1 0 0]);

% Decoding composite is much harder.

% Suppress the luma DC which ends up at subcarrier freq after demodulating.
chroma_lp_decode = firls(26, [0, chroma_bw, chroma_stop, bt601_rate] / bt601_rate, [1 1 0 0])';
ntsc_subcarrier_w = ntsc_subcarrier / (2 * bt601_rate);
subcarrier_zero = exp(2 * pi * j * ntsc_subcarrier_w);
subcarrier_notch = real(conv([1, -subcarrier_zero], [1, -conj(subcarrier_zero)]));
subcarrier_notch = subcarrier_notch' / sum(subcarrier_notch);
chroma_lp_decode = conv(chroma_lp_decode, subcarrier_notch);

% Suppress the carrier when decoding luma. This leads to less detail in luma.
% Main options are multi-line comb filters, etc.
luma_lp_decode = fir1(28, 0.3689, 'low', kaiser(29, 8.0));
subcarrier_notch = real(conv([1, -subcarrier_zero], [1, -conj(subcarrier_zero)]));
subcarrier_notch = subcarrier_notch' / sum(subcarrier_notch);
luma_lp_decode = conv(luma_lp_decode, subcarrier_notch)';

% Suppress harmonics of subcarrier which arise when demodulating.
ntsc_subcarrier_w = 2.0 * ntsc_subcarrier / (2 * bt601_rate);
subcarrier_zero = exp(2 * pi * j * ntsc_subcarrier_w);
subcarrier_notch = real(conv([1, -subcarrier_zero], [1, -conj(subcarrier_zero)]));
subcarrier_notch = subcarrier_notch' / sum(subcarrier_notch);
chroma_lp_decode = conv(chroma_lp_decode, subcarrier_notch)';

h = figure();
set(h, 'Name', 'NTSC Y encode filter @ 27 MHz');
freqz(luma_lp_encode);

h = figure();
set(h, 'Name', 'NTSC UV encode filter @ 27 MHz');
freqz(chroma_lp_encode);

h = figure();
set(h, 'Name', 'NTSC Y decode filter @ 27 MHz');
freqz(luma_lp_decode);

h = figure();
set(h, 'Name', 'NTSC UV decode filter @ 27 MHz');
freqz(chroma_lp_decode);

assert(length(downsampling_filter) == 15, "Length must be 15");
assert(length(luma_lp_encode) == 31, "Length must be 31");
assert(length(chroma_lp_encode) == 31, "Length must be 31");
assert(length(luma_lp_decode) == 31, "Length must be 31");
assert(length(chroma_lp_decode) == 31, "Length must be 31");

printf("// Autogenerated by generate_ntsc_filters.m\n");
printf("const float DownsamplingKernel[16] = float[](\n");
printf("    0.0,\n");
printf("    %.8f,\n", downsampling_filter(1:14));
printf("    %.8f);\n", downsampling_filter(15));
printf("\n");
printf("const float LumaEncodeNTSC[31] = float[](\n");
printf("    %.8f,\n", luma_lp_encode(1:30));
printf("    %.8f);\n", luma_lp_encode(31));
printf("\n");
printf("const float ChromaEncodeNTSC[31] = float[](\n");
printf("    %.8f,\n", chroma_lp_encode(1:30));
printf("    %.8f);\n", chroma_lp_encode(31));
printf("\n");
printf("const float LumaDecodeNTSC[31] = float[](\n");
printf("    %.8f,\n", luma_lp_decode(1:30));
printf("    %.8f);\n", luma_lp_decode(31));
printf("\n");
printf("const float ChromaDecodeNTSC[31] = float[](\n");
printf("    %.8f,\n", chroma_lp_decode(1:30));
printf("    %.8f);\n", chroma_lp_decode(31));
printf("\n");
printf("////////\n");

% Test some signals.

F = 0.5e6;
y = 0.5 + 0.5 * sin((2 * pi * F / subpixel_rate) * [1 : 8 * 1024]);
u = 0.2 + 0.3 * sin((2 * pi * F / subpixel_rate) * [1 : 8 * 1024]);
v = 0.3 + 0.4 * sin((2 * pi * F / subpixel_rate) * [1 : 8 * 1024]);

% Filter and decimate.
y = conv(y, downsampling_filter)(:, 1:2:end);
u = conv(u, downsampling_filter)(:, 1:2:end);
v = conv(v, downsampling_filter)(:, 1:2:end);

% Low pass filter into target bandwidth.
y = conv(y, luma_lp_encode);
u = conv(u, chroma_lp_encode);
v = conv(v, chroma_lp_encode);

u = u .* cos((2 * pi * ntsc_subcarrier / (2 * bt601_rate)) * [0 : length(u) - 1]);
v = v .* sin((2 * pi * ntsc_subcarrier / (2 * bt601_rate)) * [0 : length(v) - 1]);
c = u + v;

composite_signal = y + c;

% Reconstruct YUV

y = conv(luma_lp_decode, composite_signal);
u = 2 * conv(chroma_lp_decode, composite_signal .* cos((2 * pi * ntsc_subcarrier / (2 * bt601_rate)) * [0 : length(composite_signal) - 1]));
v = 2 * conv(chroma_lp_decode, composite_signal .* sin((2 * pi * ntsc_subcarrier / (2 * bt601_rate)) * [0 : length(composite_signal) - 1]));

h = figure();
set(h, 'Name', 'Composite signal')
plot(composite_signal);

h = figure();
set(h, 'Name', 'Reconstructed Y')
plot(y);

h = figure();
set(h, 'Name', 'Reconstructed U')
plot(u);

h = figure();
set(h, 'Name', 'Reconstructed V')
plot(v);

