// Autogenerated from slangmosh, do not edit.
#ifndef SLANGMOSH_GENERATED_Analogiface_H
#define SLANGMOSH_GENERATED_Analogiface_H
#include <stdint.h>
namespace Vulkan
{
class Program;
class Shader;
}

namespace Analog
{
template <typename Program = Vulkan::Program *, typename Shader = Vulkan::Shader *>
struct Shaders
{
	Program composite = {};
	Shader blit = {};
	Shader bloom = {};
	Shader scan = {};
	Shader sinc[2] = {};
	Shaders() = default;

	template <typename Device, typename Layout, typename Resolver>
	Shaders(Device &device, Layout &layout, const Resolver &resolver);
};
}
#endif
